### ISSUE TITLE
Exception with 4.0.1 when constraint start time using sunset

### ISSUE THREAD

**Issue by jwelter1971** [danobot/entity-controller#56]
When we reach the start time of a constraint based off sunset we get some exceptions below.

This is new with 4.0.1 and no configuration changes.

(19:47 is sunset)

```
2019-06-16 19:47:47 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entity_controller/__init__.py", line 853, in start_time_callback
    self.blocked()
AttributeError: 'Model' object has no attribute 'blocked'
2019-06-16 19:47:47 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entity_controller/__init__.py", line 853, in start_time_callback
    self.blocked()
AttributeError: 'Model' object has no attribute 'blocked'
2019-06-16 19:48:11 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entity_controller/__init__.py", line 853, in start_time_callback
    self.blocked()
AttributeError: 'Model' object has no attribute 'blocked'
2019-06-16 19:48:11 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entity_controller/__init__.py", line 855, in start_time_callback
    self.enable()
  File "/usr/local/lib/python3.7/site-packages/transitions/core.py", line 383, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python3.7/site-packages/transitions/core.py", line 1047, in _process
    return trigger()
  File "/usr/local/lib/python3.7/site-packages/transitions/extensions/nesting.py", line 251, in _trigger
    raise MachineError(msg)
transitions.core.MachineError: "Can't trigger event enable from state idle!"
2019-06-16 19:48:11 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entity_controller/__init__.py", line 853, in start_time_callback
    self.blocked()
AttributeError: 'Model' object has no attribute 'blocked'
2019-06-16 19:48:11 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/entity_controller/__init__.py", line 855, in start_time_callback
    self.enable()
  File "/usr/local/lib/python3.7/site-packages/transitions/core.py", line 383, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python3.7/site-packages/transitions/core.py", line 1047, in _process
    return trigger()
  File "/usr/local/lib/python3.7/site-packages/transitions/extensions/nesting.py", line 251, in _trigger
    raise MachineError(msg)
transitions.core.MachineError: "Can't trigger event enable from state idle!"

```

**Comment by danobot** [comment]
Did you upgrade home assistant in the meantime? Please try to use the previous version and monitor if the problem is happening. There have been no code changes that would impact integration to the `sun` component.

**Comment by jwelter1971** [comment]
I see that inside HA the sun component was changed between 0.93 --> 0.94 so perhaps that is it.  Looks like they reduced it's update frequency based on time of day....

See: https://github.com/home-assistant/home-assistant/pull/23832

**Comment by jwelter1971** [comment]
Switched to just use times and not sun offsets and working fine with 4.0.1.  Using sunset and sunrise without offsets seems to be fine.

**Comment by elupus** [comment]
Same exception with following config:
```
motion_light_tvattstuga:
  sensor: binary_sensor.rorelsesensor_tvattstuga
  entity: light.takbelysning_tvattstuga
  start_time: sunset
  end_time: sunrise
  delay: 60
  service_data:
    brightness: 80
```

**Comment by danobot** [comment]
Change your manifest file and add the sun component as a dependency. THis make HA initialise `sun` before `entity_controller`. Let me know if that works

**Comment by danobot** [comment]
any updates on this?
I am unable to reproduce.

**Comment by danobot** [comment]
Cannot reproduce, no response.
